### ISSUE TITLE
Exception when extracting 10/28

### ISSUE THREAD

**Issue by tommycahir** [FastEddyCurrent/zap2xml#9]
I get the following error when running the script, it always seems to stop at the same position

2016-10-14 16:23:44,526 Getting: http://tvschedule.zap2it.com/tvlistings/ZCGrid.do?isDescriptionOn=true&fromTimeInMillis=1476637200000&aid=tvschedule
2016-10-14 16:23:47,315 Exception
2016-10-14 16:23:47,321 Traceback (most recent call last):
File "zap2xml.py", line 1916, in main
parseGrid(fn) #data read in and unicode it
File "zap2xml.py", line 1082, in parseGrid
p.feed(b)
File "/usr/lib/python2.7/HTMLParser.py", line 117, in feed
File "/usr/lib/python2.7/HTMLParser.py", line 161, in goahead
File "/usr/lib/python2.7/HTMLParser.py", line 327, in parse_starttag
File "zap2xml.py", line 704, in handle_starttag
globals()'on_%s' % tag
File "zap2xml.py", line 323, in on_td
if re.search("^MV",cp):
File "/usr/lib/python2.7/re.py", line 146, in search
TypeError: expected string or buffer

**Comment by Schmell** [comment]
Did you install mechanize? Also dd you populate the .zap2xmlrc file with good account info?

**Comment by tommycahir** [comment]
Hi,
Yes mechanize was installed as gave an error on 1st run. 
.zap2xmlrc was filled with username and password.. Even managed to get it logged in and extract 9of28 parts.. 

Thanks for the repky

**Comment by Schmell** [comment]
i read this in the code right before the parseGrid(fn).
`# Note about the string/unicode Python 2.7 issue`
`# Found data from mechanize browser is a string with out of range bytes`
`# that can't be  converted to unicode`
`# After zip writing the html and reading it I can unicode it without error (magic)`
`# Avoid the unicode ascii error on the xml file write by using codec.open, codec.write`

are you parsing language other than english? or some strange characters?? im just stabbing at the dark here. and i don't know how to use "codec.open codec.write"

**Comment by tommycahir** [comment]
Thanks for the tip will have a look and see if I can find something about codec.open, codec.write
I am parsing in english and can do it with the Perl script on another box without issues.

**Comment by tommycahir** [comment]
Edit4ever has commented on the following thread on the kodi.tv forum pointing out the issue, his latest updated code resolves the error.. 
http://forum.kodi.tv/showthread.php?tid=267022&pid=2437236#pid2437236
